main: com.hourglassprograms.discraft.Main
name: Discraft
version: 1.0.0
author: Hourglass Programs
api-version: 1.15
commands:
  hello:
    description: Test hello command
  discraft port:
    aliases: [port, d port]
    permission: discraft.port.get
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command>"
