main: com.hourglassprograms.discraft.Main
name: Discraft
version: 1.0.5
author: Hourglass Programs
api-version: 1.15
commands:
  discraft:
    description: "Use this to get the port or auth key or to link with the Discraft Server"
    aliases: [discraft help, d help]
    permission: discraft.use
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> (port:auth:link)"
  discraft link:
    description: "Use this to link with the Discraft Server using the Authkey in the config (/discraft auth)"
    aliases: d link
    permission: discraft.use
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> link"
  discraft port:
    aliases: d port
    description: "Use this to find the port that the server runs on"
    permission: discraft.use
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command>"
  discraft auth:
    aliases: d port
    description: "Use this to get the authkey set on this Discraft Server."
    permission: discraft.use
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command>"
