main: com.hourglassprograms.discraft.Main
name: Discraft
version: 1.0.14
author: Hourglass Programs
api-version: 1.15
commands:
  discraft:
    description: "Use this to get the port or auth key or to link with the Discraft Server"
    permission: discraft.use
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> (port <new port> : auth <authkey> : link : website : invite)"
  discraft link:
    description: "Use this to link with the Discraft Server using the Authkey in the config (/discraft auth <authkey>)"
    permission: discraft.link
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> link"
  discraft port:
    description: "Use this to find the port that the server runs on"
    permission: discraft.port
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <new port> "
  discraft auth:
    description: "Use this to get the authkey set on this Discraft Server."
    permission: discraft.auth
    permission-message: You do not have permission to use this command.
    usage: "Usage: /<command> <authkey>"
  discraft website:
    description: "Use this to get the link to the Discraft website. Here you can configure the bot and read the documentation."
    usage: "Usage: /<command>"
  discraft invite:
    description: "Use this to get the link to invite the Discraft bot to your Discord server."
    usage: "Usage: /<command>"
